// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUkWTMrOFWNMqkybrrwz6qmUOOTSribzw',
    appId: '1:868118137746:web:cfab1a5c6ee03cf63b4f4b',
    messagingSenderId: '868118137746',
    projectId: 'qiquiz-caf52',
    authDomain: 'qiquiz-caf52.firebaseapp.com',
    databaseURL: 'https://qiquiz-caf52-default-rtdb.firebaseio.com',
    storageBucket: 'qiquiz-caf52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz5bTAjN-g698lyJC1P0e8KaqTx31JuCM',
    appId: '1:868118137746:android:740a3888a1b2ff433b4f4b',
    messagingSenderId: '868118137746',
    projectId: 'qiquiz-caf52',
    databaseURL: 'https://qiquiz-caf52-default-rtdb.firebaseio.com',
    storageBucket: 'qiquiz-caf52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-FtPrlk9kzu2Hp8zHcQQQY8DoCRDd5yE',
    appId: '1:868118137746:ios:ca735e53615a0d8d3b4f4b',
    messagingSenderId: '868118137746',
    projectId: 'qiquiz-caf52',
    databaseURL: 'https://qiquiz-caf52-default-rtdb.firebaseio.com',
    storageBucket: 'qiquiz-caf52.appspot.com',
    iosBundleId: 'com.example.qiquizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-FtPrlk9kzu2Hp8zHcQQQY8DoCRDd5yE',
    appId: '1:868118137746:ios:d4c2b4169bcc02993b4f4b',
    messagingSenderId: '868118137746',
    projectId: 'qiquiz-caf52',
    databaseURL: 'https://qiquiz-caf52-default-rtdb.firebaseio.com',
    storageBucket: 'qiquiz-caf52.appspot.com',
    iosBundleId: 'com.example.qiquizApp.RunnerTests',
  );
}
